# With flow viz.

# Renderer parameters
img_width: 1000
img_height: 1000
# img_width: 2000 #1808
# img_height: 1328 #976
fovx: 60
fovy: 60
near: 1
far: 200000
bg_color: [0, 0, 0]
scale_factor: 1
stretch_factor: 300
stretch_dim: 0   # 0: x, 1: y, 2: z
viz_flow: true

# Transfer fn parameters
rmin: -20
rmax: 20
control_vals: [-7.0, -3.5, 3.5, 7.0]
opacity: [1.0, 0, 0, 1.0]
viz_var: ['vel']

# Transfer fn parameters
colorize: false

# Scene params
# nc_path: 'C:\UMD\render_pc\data\nasa\hurricane_sim\data_08\particles_008_hd.nc4'
nc_path: 'C:\UMD\render_pc\data\nasa\h_common_hd.nc4'
view_path: 'C:\UMD\render_pc\data\nasa\gflow_512\view.txt'
# view_path: 'C:\UMD\render_pc\data\nasa\gflow_test\view.txt'
prefiltered: false
debug: false